# Generated by Django 4.2 on 2023-04-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
